//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltimosCalculo
    {
        public int Id { get; set; }
        public double Resultado { get; set; }
        public double Entrada1 { get; set; }
        public double Entrada2 { get; set; }
        public string Operacao { get; set; }
    }
}
